<tal:block phptal:tales="php">
<div id="default-playlists-index-container">
  <div id="default-playlists-index-results" style="margin: 1em"></div>
</div>

<tal:block metal:use-macro="../../../default/views/scripts/streams/library.phtml/Default_Streams_Table"/>

<script type="text/javascript">
sandbox.server = ${structure json_encode(server)};
</script>

<script type="text/javascript">
<!--
sandbox.run = function() {
  Whispercast.Resolver.resolve(['Whispercast.table'], [], {done: function() {
    Default_Streams_Table();

    YAHOO.util.Event.onContentReady('default-playlists-index-container', function(e) {
      sandbox.table = new Whispercast.Lib.Default.Streams.Table({
        container: 'default-playlists-index-results',
        columns:
        {
          0: false
        },
        config:
        {
          dynamicData: true,
          initialLoad:{
            request: 'pageCurrent=1&pagePerPage=10&sortBy=category_name&sortOrder=1'
          },
          sortedBy:{
            key: 'category',
            dir: YAHOO.widget.DataTable.CLASS_ASC
          }
        },
        serverId: sandbox.server.id,
        links:
        [
          '<button id="default-playlists-index-results-add">'+_('Add a new playlist...')+'</button>',
          '<button id="default-playlists-index-results-reload">'+_('Reload')+'</button>'
        ],
        query:
        {
          f: {
            type: ['playlists']
          }
        }
      });

      sandbox.table.run(Whispercast.closure(this, function() {
        YAHOO.util.Event.on('default-playlists-index-results-add', 'click', function() {
          Whispercast.App.retrieveContent('',Whispercast.Uri.buildZend('default', 'playlists', 'add', sandbox.server.id));
        });
        YAHOO.util.Event.on('default-playlists-index-results-reload', 'click', function() {
          sandbox.table.reload();
        });

        sandbox.initialized ? sandbox.initialized.call(sandbox) : false;
      }));
    });
  }});
};
sandbox.destroy = function() {
  if (sandbox.table) {
    sandbox.table.destroy();
  }

  YAHOO.util.Event.purgeElement(document.getElementById('default-playlists-index-container'), true);
  sandbox.destroyed ? sandbox.destroyed.call(sandbox) : false;
};
//-->
</script>
</tal:block>
