<tal:block phptal:tales="php">
<script type="text/javascript">
sandbox.server = ${structure json_encode(server)};
sandbox.record = ${structure json_encode(model.record)};
</script>

<script type="text/javascript">
<!--
sandbox.run = function() {
  if (sandbox.record) {
    Whispercast.Resolver.resolve(['Whispercast.dialog'], [], {done:function() {
      sandbox.dialog = new Whispercast.Dialog.Prompt(
        _('Delete source...'),
        Whispercast.strformat(_('Are you sure you want to delete source "<b>%1</b>" ?'), sandbox.record.name)+
        '<div id="default-remotes-delete-errors" class="error"><hr class="display-when-invalid"/></div>',
        {
          'Yes': {
            handler: function() {
              Whispercast.Progress.show('default-remotes-delete', sandbox.dialog.getDialog().body.parentNode, undefined, 1000);

              YAHOO.util.Connect.asyncRequest(
                'POST',
                Whispercast.Uri.buildZend('default', 'remotes', 'delete', sandbox.server.id, {id:sandbox.record.id,format:'json'}),
                {
                  success: function(o) {
                    var response = Whispercast.eval('return ('+o.responseText+')');
                    if (response.model.result > 0) {
                      Whispercast.Notifier.notify('default.streams', 'delete', sandbox.record.id);
                      sandbox.dialog.hide();
                    } else {
                      Whispercast.Errors.setMessage('default-remotes-delete-errors', response.model.errors);
                    }
                    Whispercast.Progress.hide('default-remotes-delete');
                  },
                  failure: function(o) {
                    Whispercast.Errors.setMessage('default-remotes-delete-errors', YAHOO.util.Connect.formatRequestError(o));
                    Whispercast.Progress.hide('default-remotes-delete');
                  }
                },
                'id='+sandbox.record.id
              );
            },
            isDefault: true
          },
          'Cancel': {
          }
        }
      );
      sandbox.dialog.show();
      sandbox.initialized ? sandbox.initialized.call(sandbox) : false;
    }});
  } else {
    sandbox.initialized ? sandbox.initialized.call(sandbox) : false;
  }
};
sandbox.destroy = function() {
  if (sandbox.dialog) {
    sandbox.dialog.destroy();
  }
  sandbox.destroyed ? sandbox.destroyed.call(sandbox) : false;

};
//-->
</script>
</tal:block>
